# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 656e0956bdc1e7cd8a0ac90493876428ba42d12606fb51a132dce5b8d7ddd23a89ff6fce23fdfa86a448c1507a0aa19abfb334dab75296f0aea976567d24720a

test:
  secret_key_base: 52634aaf4c91a459db468301faf9edcab1df4507c9c6bfd740918a9429cffcf78806863e4a5b38fb5df2e04dc736ead1ae001a490b89dd292fa3d3a5655fed16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
